# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Harry      
tagline:             '一个正在修行的iOS开发者'
description:         '记录iOS学习进程中的收获'
url:                 https://github.com/harry624
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Harry Wang
  url:               https://harry624.github.io
  email:             harrywang624@gmail.com

# Custom vars
version:             1.0.0
